version: '3.7'

services:
  sgde-api:
    container_name: sgde-api-container
    image: ai-sprint-sgde/sgde-api:0
    env_file:
      - .env
    # environment:
    #   - POSTGRES_USER=app
    build:
      context: sgde_api
      dockerfile: sgde_api/Dockerfile
    volumes:
      - ./sgde_api:/src/sgde_api
    ports:
      - "8000:8000"

  sgde-frontend:
    container_name: sgde-frontend-container
    image: ai-sprint-sgde/sgde-frontend:0
    build:
      context: sgde_frontend
      dockerfile: sgde_frontend/Dockerfile
    volumes:
      - ./sgde_frontend:/src/sgde_frontend
    ports:
      - "8501:8501"
    depends_on:
      - sgde-api