DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE task (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  task_name TEXT UNIQUE NOT NULL,
  description TEXT NOT NULL,
  labels TEXT NOT NULL
);

CREATE TABLE generator (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  params TEXT NOT NULL,
  task_id INTEGER NOT NULL,
  FOREIGN KEY (task_id) REFERENCES task (task_id)
);
