class Args:

    CONFIG_FILENAME = "config.py"

    BASE_APP_CONFIG = {
        "SQLALCHEMY_DATABASE_URI": "sqlite:///sgde.db"
    }

    TOKEN_EXPIRATION_SECONDS = 60 * 60 * 24

    MIN_USERNAME_LENGTH = 4
    MAX_USERNAME_LENGTH = 100
    MIN_PASSWORD_LENGTH = 10
    MAX_PASSWORD_LENGTH = 100
    MIN_TASK_NAME_LENGTH = 4
    MAX_TASK_NAME_LENGTH = 100
    MIN_GENERATOR_NAME_LENGTH = 4
    MAX_GENERATOR_NAME_LENGTH = 100

    MAX_FILE_PATH_LENGTH = 1000
