SECRET_KEY: "dev"
JWT_SECRET_KEY: "dev"

SQLALCHEMY_DATABASE_URI: "sqlite:///sgde.db"

TOKEN_EXPIRATION_SECONDS: 86400

MIN_USERNAME_LENGTH: 4
MAX_USERNAME_LENGTH: 120
MIN_PASSWORD_LENGTH: 10
MAX_PASSWORD_LENGTH: 120
MIN_TASK_NAME_LENGTH: 4
MAX_TASK_NAME_LENGTH: 120
MIN_GENERATOR_NAME_LENGTH: 4
MAX_GENERATOR_NAME_LENGTH: 120
